### ISSUE TITLE
mocha > 2.4.5 fails with reporter xunit

### ISSUE THREAD

**Issue by fry2k** [kmiyashiro/grunt-mocha#163]
Hello,

with the new release of mocha greater than 2.4.5 (current 2.5.2) my mocha task with reporter XUnit for jenkins doesn't work any more.

It fails cause of https://github.com/mochajs/mocha/commit/d4f7905dbb9d4cc65cca02373b99e5549fa7ce2a 
The Mocha XUnit Reporter https://github.com/mochajs/mocha/blob/master/lib/reporters/xunit.js was changed to get pending tests with test.isPending() instead of test.pending in the past.

For me it is not clear how I can manipulate the test object which is the parameter of 
`runner.on('pass', function(test) {})`
Maybe someone can help me fixing this issue.

**Comment by ScottFreeCode** [comment]
Furthermore, it's possible to run the exact same test with "grunt-mocha-test" or "grunt-simple-mocha" and have the XUnit reporter work fine, but with "grunt-mocha" the `isPending` function is mysteriously missing when the test is sent to the XUnit reporter.

**Comment by matthewriley** [comment]
I’m seeing the same issue with XUnit failing due to isPending(). I originally reported it with mochajs (see referenced issue above), but it appears to originate with grunt-mocha.

I have some sample code that recreates this issue.

Mocha XUnit Reporter Sample
https://github.com/matthewriley/mocha-xunit-reporter-sample

**Comment by cades** [comment]
I found the root suit (for example, [this](https://github.com/mochajs/mocha/blob/master/lib/interfaces/bdd.js#L26)) is not `instanceof` "mocha/lib/suite".

so `isPending` is not on its prototype chain. it this the root cause?

**Comment by ScottFreeCode** [comment]
That function is not inheriting Suite because it is not a suite constructor; in fact, it's even creating the root suite: it takes an existing suite as a parameter.

(You can also add `console.log` calls to the XUnit reporter to see that the tests are missing the `isPending` function.)

Additionally, the problem does not occur with Mocha itself and not with some other integrations either, so what we really need to determine is what Grunt-Mocha is doing differently.

**Comment by cades** [comment]
Sorry I didn't state it clear, I mean that the parameter itself is the root suite, not the function.

**Comment by ScottFreeCode** [comment]
Is Grunt-Mocha creating a root suite of its own without it inheriting Mocha's `Suite`? As far as I can tell, Mocha is creating the root suite here: https://github.com/mochajs/mocha/blob/master/lib/mocha.js#L85 using the `Suite` object from here: https://github.com/mochajs/mocha/blob/master/lib/mocha.js#L41

**Comment by omatic-hacker** [comment]
Hi guys, is there any workarounds for this bug? I would like to use **grunt-mocha** on my client side and generate xUnit reports, but always got: `Fatal error: test.isPending is not a function`

I really appreciate any help you can provide.

**Comment by cades** [comment]
@omatic-hacker Here's a [patch](https://github.com/garyyeap/respec-given/blob/master/mocha/patch-for-version-inconsistency.js) I wrote for my project.

**Comment by omatic-hacker** [comment]
@cades Thanks, I will try your patch!

**Comment by eugenet8k** [comment]
@omatic-hacker I fixed this problem in my fork of `grunt-mocha-blanket`(https://github.com/eugenet8k/grunt-mocha-blanket) which could be used instead of `grunt-mocha`. It's basically the same thing but with built-in `blanketjs` coverage support. Idk, maybe it will save you some time.
